### ISSUE TITLE
8.3 Cobra And Rebug 4.84.2 REX

### ISSUE THREAD

**Issue by godreborn** [Evilnat/Cobra-PS3#3] opened 2021-06-19 16:59 UTC
a friend wanted me to post this issue, but apparently, 8.3 on rebug 4.84.2 rex is causing his ps2 games not to work.  could you look into this?  thanks.

**Comment by Evilnat** [comment] 2021-06-19 21:02
I will take a look into this, I will upload a new stage2 in a few minutes. Is he in DEX or CEX mode?

**Comment by Evilnat** [comment] 2021-06-19 21:05
> a friend wanted me to post this issue, but apparently, 8.3 on rebug 4.84.2 rex is causing his ps2 games not to work. could you look into this? thanks.

What PS3 model does he have?

**Comment by godreborn** [comment] 2021-06-19 21:47
thanks.  he has a ps3 slim cech2504a Cex

**Comment by Evilnat** [comment] 2021-06-19 21:50
When he is launching a PS2 game, it shows blackscreen, "Unsupported data" or anything else?

**Comment by godreborn** [comment] 2021-06-19 22:06
Unsupported data Cobra mount not ps2 netemu

**Comment by Evilnat** [comment] 2021-06-19 22:11
The issue is caused by hashes, maybe I'm using another version of 4.84.2, can you send me the latest Rebug 4.84.2 build that your friend is using?

**Comment by godreborn** [comment] 2021-06-19 22:38
here's what he said: I use the version that can be downloaded from the Ultimate Toolbox. I can’t download it anywhere anymore

**Comment by Evilnat** [comment] 2021-06-19 22:47
Please tell him to download and install this PUP, I think it is the latest for 4.84.2 REX and it is the one that I used to port Cobra 8.3 

https://mega.nz/file/UQM2WTJR#lfuwFqZcavEIr_eBl9cIu_LickG3fVSsdeDjs0b51Co

**Comment by godreborn** [comment] 2021-06-20 11:26
alright, he said that he tried that pup, and it still doesn't work.  he said everything works but ps2 games.  and, they work with 8.2, just not 8.3.

**Comment by Evilnat** [comment] 2021-06-21 06:47
Seems that finally is fixed with the new update, thanks for reporting it ;)

**Closed by Evilnat** 2021-06-21 06:47 UTC
